<?php declare(strict_types=1);

namespace App\Characters\Infrastructure\Controller\Command;

use App\Characters\Application\Command\StoreStarWarsCharactersCommandHandler;
use App\Characters\Application\Query\GetStarWarsCharactersQueryHandler;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name: 'starwars:import')]
class GetAndStoreCharactersWithMovies extends Command
{
    public function __construct(
        private readonly GetStarWarsCharactersQueryHandler $getStarWarsCharactersQueryHandler,
        private readonly StoreStarWarsCharactersCommandHandler $storeStarWarsCharactersCommandHandler,
        string $name = null
    ) {
        parent::__construct($name);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
